# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/bertrand/Minefield/cpp/Server

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/bertrand/Minefield/cpp/Server

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bertrand/Minefield/cpp/Server/CMakeFiles /home/bertrand/Minefield/cpp/Server/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/bertrand/Minefield/cpp/Server/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Server

# Build rule for target.
Server: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Server
.PHONY : Server

# fast build rule for target.
Server/fast:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/build
.PHONY : Server/fast

src/Block/Block.o: src/Block/Block.cpp.o
.PHONY : src/Block/Block.o

# target to build an object file
src/Block/Block.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Block.cpp.o
.PHONY : src/Block/Block.cpp.o

src/Block/Block.i: src/Block/Block.cpp.i
.PHONY : src/Block/Block.i

# target to preprocess a source file
src/Block/Block.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Block.cpp.i
.PHONY : src/Block/Block.cpp.i

src/Block/Block.s: src/Block/Block.cpp.s
.PHONY : src/Block/Block.s

# target to generate assembly for a file
src/Block/Block.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Block.cpp.s
.PHONY : src/Block/Block.cpp.s

src/Block/BlockList.o: src/Block/BlockList.cpp.o
.PHONY : src/Block/BlockList.o

# target to build an object file
src/Block/BlockList.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/BlockList.cpp.o
.PHONY : src/Block/BlockList.cpp.o

src/Block/BlockList.i: src/Block/BlockList.cpp.i
.PHONY : src/Block/BlockList.i

# target to preprocess a source file
src/Block/BlockList.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/BlockList.cpp.i
.PHONY : src/Block/BlockList.cpp.i

src/Block/BlockList.s: src/Block/BlockList.cpp.s
.PHONY : src/Block/BlockList.s

# target to generate assembly for a file
src/Block/BlockList.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/BlockList.cpp.s
.PHONY : src/Block/BlockList.cpp.s

src/Block/BlockMaterial.o: src/Block/BlockMaterial.cpp.o
.PHONY : src/Block/BlockMaterial.o

# target to build an object file
src/Block/BlockMaterial.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/BlockMaterial.cpp.o
.PHONY : src/Block/BlockMaterial.cpp.o

src/Block/BlockMaterial.i: src/Block/BlockMaterial.cpp.i
.PHONY : src/Block/BlockMaterial.i

# target to preprocess a source file
src/Block/BlockMaterial.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/BlockMaterial.cpp.i
.PHONY : src/Block/BlockMaterial.cpp.i

src/Block/BlockMaterial.s: src/Block/BlockMaterial.cpp.s
.PHONY : src/Block/BlockMaterial.s

# target to generate assembly for a file
src/Block/BlockMaterial.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/BlockMaterial.cpp.s
.PHONY : src/Block/BlockMaterial.cpp.s

src/Block/Scripts/Basics/StairScript.o: src/Block/Scripts/Basics/StairScript.cpp.o
.PHONY : src/Block/Scripts/Basics/StairScript.o

# target to build an object file
src/Block/Scripts/Basics/StairScript.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Scripts/Basics/StairScript.cpp.o
.PHONY : src/Block/Scripts/Basics/StairScript.cpp.o

src/Block/Scripts/Basics/StairScript.i: src/Block/Scripts/Basics/StairScript.cpp.i
.PHONY : src/Block/Scripts/Basics/StairScript.i

# target to preprocess a source file
src/Block/Scripts/Basics/StairScript.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Scripts/Basics/StairScript.cpp.i
.PHONY : src/Block/Scripts/Basics/StairScript.cpp.i

src/Block/Scripts/Basics/StairScript.s: src/Block/Scripts/Basics/StairScript.cpp.s
.PHONY : src/Block/Scripts/Basics/StairScript.s

# target to generate assembly for a file
src/Block/Scripts/Basics/StairScript.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Scripts/Basics/StairScript.cpp.s
.PHONY : src/Block/Scripts/Basics/StairScript.cpp.s

src/Block/Scripts/BlockScript.o: src/Block/Scripts/BlockScript.cpp.o
.PHONY : src/Block/Scripts/BlockScript.o

# target to build an object file
src/Block/Scripts/BlockScript.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Scripts/BlockScript.cpp.o
.PHONY : src/Block/Scripts/BlockScript.cpp.o

src/Block/Scripts/BlockScript.i: src/Block/Scripts/BlockScript.cpp.i
.PHONY : src/Block/Scripts/BlockScript.i

# target to preprocess a source file
src/Block/Scripts/BlockScript.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Scripts/BlockScript.cpp.i
.PHONY : src/Block/Scripts/BlockScript.cpp.i

src/Block/Scripts/BlockScript.s: src/Block/Scripts/BlockScript.cpp.s
.PHONY : src/Block/Scripts/BlockScript.s

# target to generate assembly for a file
src/Block/Scripts/BlockScript.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Scripts/BlockScript.cpp.s
.PHONY : src/Block/Scripts/BlockScript.cpp.s

src/Block/Scripts/RegisterBlockScripts.o: src/Block/Scripts/RegisterBlockScripts.cpp.o
.PHONY : src/Block/Scripts/RegisterBlockScripts.o

# target to build an object file
src/Block/Scripts/RegisterBlockScripts.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Scripts/RegisterBlockScripts.cpp.o
.PHONY : src/Block/Scripts/RegisterBlockScripts.cpp.o

src/Block/Scripts/RegisterBlockScripts.i: src/Block/Scripts/RegisterBlockScripts.cpp.i
.PHONY : src/Block/Scripts/RegisterBlockScripts.i

# target to preprocess a source file
src/Block/Scripts/RegisterBlockScripts.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Scripts/RegisterBlockScripts.cpp.i
.PHONY : src/Block/Scripts/RegisterBlockScripts.cpp.i

src/Block/Scripts/RegisterBlockScripts.s: src/Block/Scripts/RegisterBlockScripts.cpp.s
.PHONY : src/Block/Scripts/RegisterBlockScripts.s

# target to generate assembly for a file
src/Block/Scripts/RegisterBlockScripts.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/Scripts/RegisterBlockScripts.cpp.s
.PHONY : src/Block/Scripts/RegisterBlockScripts.cpp.s

src/Block/SoundBlock.o: src/Block/SoundBlock.cpp.o
.PHONY : src/Block/SoundBlock.o

# target to build an object file
src/Block/SoundBlock.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/SoundBlock.cpp.o
.PHONY : src/Block/SoundBlock.cpp.o

src/Block/SoundBlock.i: src/Block/SoundBlock.cpp.i
.PHONY : src/Block/SoundBlock.i

# target to preprocess a source file
src/Block/SoundBlock.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/SoundBlock.cpp.i
.PHONY : src/Block/SoundBlock.cpp.i

src/Block/SoundBlock.s: src/Block/SoundBlock.cpp.s
.PHONY : src/Block/SoundBlock.s

# target to generate assembly for a file
src/Block/SoundBlock.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Block/SoundBlock.cpp.s
.PHONY : src/Block/SoundBlock.cpp.s

src/Chat/ChatManager.o: src/Chat/ChatManager.cpp.o
.PHONY : src/Chat/ChatManager.o

# target to build an object file
src/Chat/ChatManager.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Chat/ChatManager.cpp.o
.PHONY : src/Chat/ChatManager.cpp.o

src/Chat/ChatManager.i: src/Chat/ChatManager.cpp.i
.PHONY : src/Chat/ChatManager.i

# target to preprocess a source file
src/Chat/ChatManager.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Chat/ChatManager.cpp.i
.PHONY : src/Chat/ChatManager.cpp.i

src/Chat/ChatManager.s: src/Chat/ChatManager.cpp.s
.PHONY : src/Chat/ChatManager.s

# target to generate assembly for a file
src/Chat/ChatManager.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Chat/ChatManager.cpp.s
.PHONY : src/Chat/ChatManager.cpp.s

src/Config/Config.o: src/Config/Config.cpp.o
.PHONY : src/Config/Config.o

# target to build an object file
src/Config/Config.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Config/Config.cpp.o
.PHONY : src/Config/Config.cpp.o

src/Config/Config.i: src/Config/Config.cpp.i
.PHONY : src/Config/Config.i

# target to preprocess a source file
src/Config/Config.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Config/Config.cpp.i
.PHONY : src/Config/Config.cpp.i

src/Config/Config.s: src/Config/Config.cpp.s
.PHONY : src/Config/Config.s

# target to generate assembly for a file
src/Config/Config.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Config/Config.cpp.s
.PHONY : src/Config/Config.cpp.s

src/Database/DatabaseManager.o: src/Database/DatabaseManager.cpp.o
.PHONY : src/Database/DatabaseManager.o

# target to build an object file
src/Database/DatabaseManager.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Database/DatabaseManager.cpp.o
.PHONY : src/Database/DatabaseManager.cpp.o

src/Database/DatabaseManager.i: src/Database/DatabaseManager.cpp.i
.PHONY : src/Database/DatabaseManager.i

# target to preprocess a source file
src/Database/DatabaseManager.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Database/DatabaseManager.cpp.i
.PHONY : src/Database/DatabaseManager.cpp.i

src/Database/DatabaseManager.s: src/Database/DatabaseManager.cpp.s
.PHONY : src/Database/DatabaseManager.s

# target to generate assembly for a file
src/Database/DatabaseManager.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Database/DatabaseManager.cpp.s
.PHONY : src/Database/DatabaseManager.cpp.s

src/Entity/Entity.o: src/Entity/Entity.cpp.o
.PHONY : src/Entity/Entity.o

# target to build an object file
src/Entity/Entity.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/Entity.cpp.o
.PHONY : src/Entity/Entity.cpp.o

src/Entity/Entity.i: src/Entity/Entity.cpp.i
.PHONY : src/Entity/Entity.i

# target to preprocess a source file
src/Entity/Entity.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/Entity.cpp.i
.PHONY : src/Entity/Entity.cpp.i

src/Entity/Entity.s: src/Entity/Entity.cpp.s
.PHONY : src/Entity/Entity.s

# target to generate assembly for a file
src/Entity/Entity.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/Entity.cpp.s
.PHONY : src/Entity/Entity.cpp.s

src/Entity/EntityPlayer.o: src/Entity/EntityPlayer.cpp.o
.PHONY : src/Entity/EntityPlayer.o

# target to build an object file
src/Entity/EntityPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/EntityPlayer.cpp.o
.PHONY : src/Entity/EntityPlayer.cpp.o

src/Entity/EntityPlayer.i: src/Entity/EntityPlayer.cpp.i
.PHONY : src/Entity/EntityPlayer.i

# target to preprocess a source file
src/Entity/EntityPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/EntityPlayer.cpp.i
.PHONY : src/Entity/EntityPlayer.cpp.i

src/Entity/EntityPlayer.s: src/Entity/EntityPlayer.cpp.s
.PHONY : src/Entity/EntityPlayer.s

# target to generate assembly for a file
src/Entity/EntityPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/EntityPlayer.cpp.s
.PHONY : src/Entity/EntityPlayer.cpp.s

src/Entity/LivingEntity.o: src/Entity/LivingEntity.cpp.o
.PHONY : src/Entity/LivingEntity.o

# target to build an object file
src/Entity/LivingEntity.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/LivingEntity.cpp.o
.PHONY : src/Entity/LivingEntity.cpp.o

src/Entity/LivingEntity.i: src/Entity/LivingEntity.cpp.i
.PHONY : src/Entity/LivingEntity.i

# target to preprocess a source file
src/Entity/LivingEntity.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/LivingEntity.cpp.i
.PHONY : src/Entity/LivingEntity.cpp.i

src/Entity/LivingEntity.s: src/Entity/LivingEntity.cpp.s
.PHONY : src/Entity/LivingEntity.s

# target to generate assembly for a file
src/Entity/LivingEntity.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/LivingEntity.cpp.s
.PHONY : src/Entity/LivingEntity.cpp.s

src/Entity/Position.o: src/Entity/Position.cpp.o
.PHONY : src/Entity/Position.o

# target to build an object file
src/Entity/Position.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/Position.cpp.o
.PHONY : src/Entity/Position.cpp.o

src/Entity/Position.i: src/Entity/Position.cpp.i
.PHONY : src/Entity/Position.i

# target to preprocess a source file
src/Entity/Position.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/Position.cpp.i
.PHONY : src/Entity/Position.cpp.i

src/Entity/Position.s: src/Entity/Position.cpp.s
.PHONY : src/Entity/Position.s

# target to generate assembly for a file
src/Entity/Position.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Entity/Position.cpp.s
.PHONY : src/Entity/Position.cpp.s

src/Inventory/Inventory.o: src/Inventory/Inventory.cpp.o
.PHONY : src/Inventory/Inventory.o

# target to build an object file
src/Inventory/Inventory.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Inventory.cpp.o
.PHONY : src/Inventory/Inventory.cpp.o

src/Inventory/Inventory.i: src/Inventory/Inventory.cpp.i
.PHONY : src/Inventory/Inventory.i

# target to preprocess a source file
src/Inventory/Inventory.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Inventory.cpp.i
.PHONY : src/Inventory/Inventory.cpp.i

src/Inventory/Inventory.s: src/Inventory/Inventory.cpp.s
.PHONY : src/Inventory/Inventory.s

# target to generate assembly for a file
src/Inventory/Inventory.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Inventory.cpp.s
.PHONY : src/Inventory/Inventory.cpp.s

src/Inventory/InventoryPlayer.o: src/Inventory/InventoryPlayer.cpp.o
.PHONY : src/Inventory/InventoryPlayer.o

# target to build an object file
src/Inventory/InventoryPlayer.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/InventoryPlayer.cpp.o
.PHONY : src/Inventory/InventoryPlayer.cpp.o

src/Inventory/InventoryPlayer.i: src/Inventory/InventoryPlayer.cpp.i
.PHONY : src/Inventory/InventoryPlayer.i

# target to preprocess a source file
src/Inventory/InventoryPlayer.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/InventoryPlayer.cpp.i
.PHONY : src/Inventory/InventoryPlayer.cpp.i

src/Inventory/InventoryPlayer.s: src/Inventory/InventoryPlayer.cpp.s
.PHONY : src/Inventory/InventoryPlayer.s

# target to generate assembly for a file
src/Inventory/InventoryPlayer.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/InventoryPlayer.cpp.s
.PHONY : src/Inventory/InventoryPlayer.cpp.s

src/Inventory/Item.o: src/Inventory/Item.cpp.o
.PHONY : src/Inventory/Item.o

# target to build an object file
src/Inventory/Item.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Item.cpp.o
.PHONY : src/Inventory/Item.cpp.o

src/Inventory/Item.i: src/Inventory/Item.cpp.i
.PHONY : src/Inventory/Item.i

# target to preprocess a source file
src/Inventory/Item.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Item.cpp.i
.PHONY : src/Inventory/Item.cpp.i

src/Inventory/Item.s: src/Inventory/Item.cpp.s
.PHONY : src/Inventory/Item.s

# target to generate assembly for a file
src/Inventory/Item.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Item.cpp.s
.PHONY : src/Inventory/Item.cpp.s

src/Inventory/ItemStack.o: src/Inventory/ItemStack.cpp.o
.PHONY : src/Inventory/ItemStack.o

# target to build an object file
src/Inventory/ItemStack.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/ItemStack.cpp.o
.PHONY : src/Inventory/ItemStack.cpp.o

src/Inventory/ItemStack.i: src/Inventory/ItemStack.cpp.i
.PHONY : src/Inventory/ItemStack.i

# target to preprocess a source file
src/Inventory/ItemStack.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/ItemStack.cpp.i
.PHONY : src/Inventory/ItemStack.cpp.i

src/Inventory/ItemStack.s: src/Inventory/ItemStack.cpp.s
.PHONY : src/Inventory/ItemStack.s

# target to generate assembly for a file
src/Inventory/ItemStack.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/ItemStack.cpp.s
.PHONY : src/Inventory/ItemStack.cpp.s

src/Inventory/Scripts/Basics/ItemBlockScript.o: src/Inventory/Scripts/Basics/ItemBlockScript.cpp.o
.PHONY : src/Inventory/Scripts/Basics/ItemBlockScript.o

# target to build an object file
src/Inventory/Scripts/Basics/ItemBlockScript.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Scripts/Basics/ItemBlockScript.cpp.o
.PHONY : src/Inventory/Scripts/Basics/ItemBlockScript.cpp.o

src/Inventory/Scripts/Basics/ItemBlockScript.i: src/Inventory/Scripts/Basics/ItemBlockScript.cpp.i
.PHONY : src/Inventory/Scripts/Basics/ItemBlockScript.i

# target to preprocess a source file
src/Inventory/Scripts/Basics/ItemBlockScript.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Scripts/Basics/ItemBlockScript.cpp.i
.PHONY : src/Inventory/Scripts/Basics/ItemBlockScript.cpp.i

src/Inventory/Scripts/Basics/ItemBlockScript.s: src/Inventory/Scripts/Basics/ItemBlockScript.cpp.s
.PHONY : src/Inventory/Scripts/Basics/ItemBlockScript.s

# target to generate assembly for a file
src/Inventory/Scripts/Basics/ItemBlockScript.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Scripts/Basics/ItemBlockScript.cpp.s
.PHONY : src/Inventory/Scripts/Basics/ItemBlockScript.cpp.s

src/Inventory/Scripts/ItemScript.o: src/Inventory/Scripts/ItemScript.cpp.o
.PHONY : src/Inventory/Scripts/ItemScript.o

# target to build an object file
src/Inventory/Scripts/ItemScript.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Scripts/ItemScript.cpp.o
.PHONY : src/Inventory/Scripts/ItemScript.cpp.o

src/Inventory/Scripts/ItemScript.i: src/Inventory/Scripts/ItemScript.cpp.i
.PHONY : src/Inventory/Scripts/ItemScript.i

# target to preprocess a source file
src/Inventory/Scripts/ItemScript.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Scripts/ItemScript.cpp.i
.PHONY : src/Inventory/Scripts/ItemScript.cpp.i

src/Inventory/Scripts/ItemScript.s: src/Inventory/Scripts/ItemScript.cpp.s
.PHONY : src/Inventory/Scripts/ItemScript.s

# target to generate assembly for a file
src/Inventory/Scripts/ItemScript.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Scripts/ItemScript.cpp.s
.PHONY : src/Inventory/Scripts/ItemScript.cpp.s

src/Inventory/Scripts/RegisterItemScripts.o: src/Inventory/Scripts/RegisterItemScripts.cpp.o
.PHONY : src/Inventory/Scripts/RegisterItemScripts.o

# target to build an object file
src/Inventory/Scripts/RegisterItemScripts.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Scripts/RegisterItemScripts.cpp.o
.PHONY : src/Inventory/Scripts/RegisterItemScripts.cpp.o

src/Inventory/Scripts/RegisterItemScripts.i: src/Inventory/Scripts/RegisterItemScripts.cpp.i
.PHONY : src/Inventory/Scripts/RegisterItemScripts.i

# target to preprocess a source file
src/Inventory/Scripts/RegisterItemScripts.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Scripts/RegisterItemScripts.cpp.i
.PHONY : src/Inventory/Scripts/RegisterItemScripts.cpp.i

src/Inventory/Scripts/RegisterItemScripts.s: src/Inventory/Scripts/RegisterItemScripts.cpp.s
.PHONY : src/Inventory/Scripts/RegisterItemScripts.s

# target to generate assembly for a file
src/Inventory/Scripts/RegisterItemScripts.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Inventory/Scripts/RegisterItemScripts.cpp.s
.PHONY : src/Inventory/Scripts/RegisterItemScripts.cpp.s

src/Main/Server.o: src/Main/Server.cpp.o
.PHONY : src/Main/Server.o

# target to build an object file
src/Main/Server.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Main/Server.cpp.o
.PHONY : src/Main/Server.cpp.o

src/Main/Server.i: src/Main/Server.cpp.i
.PHONY : src/Main/Server.i

# target to preprocess a source file
src/Main/Server.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Main/Server.cpp.i
.PHONY : src/Main/Server.cpp.i

src/Main/Server.s: src/Main/Server.cpp.s
.PHONY : src/Main/Server.s

# target to generate assembly for a file
src/Main/Server.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Main/Server.cpp.s
.PHONY : src/Main/Server.cpp.s

src/Network/NetworkEncryption.o: src/Network/NetworkEncryption.cpp.o
.PHONY : src/Network/NetworkEncryption.o

# target to build an object file
src/Network/NetworkEncryption.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkEncryption.cpp.o
.PHONY : src/Network/NetworkEncryption.cpp.o

src/Network/NetworkEncryption.i: src/Network/NetworkEncryption.cpp.i
.PHONY : src/Network/NetworkEncryption.i

# target to preprocess a source file
src/Network/NetworkEncryption.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkEncryption.cpp.i
.PHONY : src/Network/NetworkEncryption.cpp.i

src/Network/NetworkEncryption.s: src/Network/NetworkEncryption.cpp.s
.PHONY : src/Network/NetworkEncryption.s

# target to generate assembly for a file
src/Network/NetworkEncryption.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkEncryption.cpp.s
.PHONY : src/Network/NetworkEncryption.cpp.s

src/Network/NetworkException.o: src/Network/NetworkException.cpp.o
.PHONY : src/Network/NetworkException.o

# target to build an object file
src/Network/NetworkException.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkException.cpp.o
.PHONY : src/Network/NetworkException.cpp.o

src/Network/NetworkException.i: src/Network/NetworkException.cpp.i
.PHONY : src/Network/NetworkException.i

# target to preprocess a source file
src/Network/NetworkException.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkException.cpp.i
.PHONY : src/Network/NetworkException.cpp.i

src/Network/NetworkException.s: src/Network/NetworkException.cpp.s
.PHONY : src/Network/NetworkException.s

# target to generate assembly for a file
src/Network/NetworkException.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkException.cpp.s
.PHONY : src/Network/NetworkException.cpp.s

src/Network/NetworkExceptionData.o: src/Network/NetworkExceptionData.cpp.o
.PHONY : src/Network/NetworkExceptionData.o

# target to build an object file
src/Network/NetworkExceptionData.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkExceptionData.cpp.o
.PHONY : src/Network/NetworkExceptionData.cpp.o

src/Network/NetworkExceptionData.i: src/Network/NetworkExceptionData.cpp.i
.PHONY : src/Network/NetworkExceptionData.i

# target to preprocess a source file
src/Network/NetworkExceptionData.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkExceptionData.cpp.i
.PHONY : src/Network/NetworkExceptionData.cpp.i

src/Network/NetworkExceptionData.s: src/Network/NetworkExceptionData.cpp.s
.PHONY : src/Network/NetworkExceptionData.s

# target to generate assembly for a file
src/Network/NetworkExceptionData.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkExceptionData.cpp.s
.PHONY : src/Network/NetworkExceptionData.cpp.s

src/Network/NetworkManager.o: src/Network/NetworkManager.cpp.o
.PHONY : src/Network/NetworkManager.o

# target to build an object file
src/Network/NetworkManager.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkManager.cpp.o
.PHONY : src/Network/NetworkManager.cpp.o

src/Network/NetworkManager.i: src/Network/NetworkManager.cpp.i
.PHONY : src/Network/NetworkManager.i

# target to preprocess a source file
src/Network/NetworkManager.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkManager.cpp.i
.PHONY : src/Network/NetworkManager.cpp.i

src/Network/NetworkManager.s: src/Network/NetworkManager.cpp.s
.PHONY : src/Network/NetworkManager.s

# target to generate assembly for a file
src/Network/NetworkManager.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkManager.cpp.s
.PHONY : src/Network/NetworkManager.cpp.s

src/Network/NetworkPacket.o: src/Network/NetworkPacket.cpp.o
.PHONY : src/Network/NetworkPacket.o

# target to build an object file
src/Network/NetworkPacket.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkPacket.cpp.o
.PHONY : src/Network/NetworkPacket.cpp.o

src/Network/NetworkPacket.i: src/Network/NetworkPacket.cpp.i
.PHONY : src/Network/NetworkPacket.i

# target to preprocess a source file
src/Network/NetworkPacket.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkPacket.cpp.i
.PHONY : src/Network/NetworkPacket.cpp.i

src/Network/NetworkPacket.s: src/Network/NetworkPacket.cpp.s
.PHONY : src/Network/NetworkPacket.s

# target to generate assembly for a file
src/Network/NetworkPacket.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkPacket.cpp.s
.PHONY : src/Network/NetworkPacket.cpp.s

src/Network/NetworkSession.o: src/Network/NetworkSession.cpp.o
.PHONY : src/Network/NetworkSession.o

# target to build an object file
src/Network/NetworkSession.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkSession.cpp.o
.PHONY : src/Network/NetworkSession.cpp.o

src/Network/NetworkSession.i: src/Network/NetworkSession.cpp.i
.PHONY : src/Network/NetworkSession.i

# target to preprocess a source file
src/Network/NetworkSession.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkSession.cpp.i
.PHONY : src/Network/NetworkSession.cpp.i

src/Network/NetworkSession.s: src/Network/NetworkSession.cpp.s
.PHONY : src/Network/NetworkSession.s

# target to generate assembly for a file
src/Network/NetworkSession.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/NetworkSession.cpp.s
.PHONY : src/Network/NetworkSession.cpp.s

src/Network/Opcode.o: src/Network/Opcode.cpp.o
.PHONY : src/Network/Opcode.o

# target to build an object file
src/Network/Opcode.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/Opcode.cpp.o
.PHONY : src/Network/Opcode.cpp.o

src/Network/Opcode.i: src/Network/Opcode.cpp.i
.PHONY : src/Network/Opcode.i

# target to preprocess a source file
src/Network/Opcode.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/Opcode.cpp.i
.PHONY : src/Network/Opcode.cpp.i

src/Network/Opcode.s: src/Network/Opcode.cpp.s
.PHONY : src/Network/Opcode.s

# target to generate assembly for a file
src/Network/Opcode.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/Opcode.cpp.s
.PHONY : src/Network/Opcode.cpp.s

src/Network/PacketHandler.o: src/Network/PacketHandler.cpp.o
.PHONY : src/Network/PacketHandler.o

# target to build an object file
src/Network/PacketHandler.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/PacketHandler.cpp.o
.PHONY : src/Network/PacketHandler.cpp.o

src/Network/PacketHandler.i: src/Network/PacketHandler.cpp.i
.PHONY : src/Network/PacketHandler.i

# target to preprocess a source file
src/Network/PacketHandler.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/PacketHandler.cpp.i
.PHONY : src/Network/PacketHandler.cpp.i

src/Network/PacketHandler.s: src/Network/PacketHandler.cpp.s
.PHONY : src/Network/PacketHandler.s

# target to generate assembly for a file
src/Network/PacketHandler.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Network/PacketHandler.cpp.s
.PHONY : src/Network/PacketHandler.cpp.s

src/Scripting/ScriptManager.o: src/Scripting/ScriptManager.cpp.o
.PHONY : src/Scripting/ScriptManager.o

# target to build an object file
src/Scripting/ScriptManager.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Scripting/ScriptManager.cpp.o
.PHONY : src/Scripting/ScriptManager.cpp.o

src/Scripting/ScriptManager.i: src/Scripting/ScriptManager.cpp.i
.PHONY : src/Scripting/ScriptManager.i

# target to preprocess a source file
src/Scripting/ScriptManager.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Scripting/ScriptManager.cpp.i
.PHONY : src/Scripting/ScriptManager.cpp.i

src/Scripting/ScriptManager.s: src/Scripting/ScriptManager.cpp.s
.PHONY : src/Scripting/ScriptManager.s

# target to generate assembly for a file
src/Scripting/ScriptManager.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Scripting/ScriptManager.cpp.s
.PHONY : src/Scripting/ScriptManager.cpp.s

src/Util/AABB.o: src/Util/AABB.cpp.o
.PHONY : src/Util/AABB.o

# target to build an object file
src/Util/AABB.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Util/AABB.cpp.o
.PHONY : src/Util/AABB.cpp.o

src/Util/AABB.i: src/Util/AABB.cpp.i
.PHONY : src/Util/AABB.i

# target to preprocess a source file
src/Util/AABB.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Util/AABB.cpp.i
.PHONY : src/Util/AABB.cpp.i

src/Util/AABB.s: src/Util/AABB.cpp.s
.PHONY : src/Util/AABB.s

# target to generate assembly for a file
src/Util/AABB.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/Util/AABB.cpp.s
.PHONY : src/Util/AABB.cpp.s

src/World/Chunk.o: src/World/Chunk.cpp.o
.PHONY : src/World/Chunk.o

# target to build an object file
src/World/Chunk.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/Chunk.cpp.o
.PHONY : src/World/Chunk.cpp.o

src/World/Chunk.i: src/World/Chunk.cpp.i
.PHONY : src/World/Chunk.i

# target to preprocess a source file
src/World/Chunk.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/Chunk.cpp.i
.PHONY : src/World/Chunk.cpp.i

src/World/Chunk.s: src/World/Chunk.cpp.s
.PHONY : src/World/Chunk.s

# target to generate assembly for a file
src/World/Chunk.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/Chunk.cpp.s
.PHONY : src/World/Chunk.cpp.s

src/World/VirtualChunk.o: src/World/VirtualChunk.cpp.o
.PHONY : src/World/VirtualChunk.o

# target to build an object file
src/World/VirtualChunk.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/VirtualChunk.cpp.o
.PHONY : src/World/VirtualChunk.cpp.o

src/World/VirtualChunk.i: src/World/VirtualChunk.cpp.i
.PHONY : src/World/VirtualChunk.i

# target to preprocess a source file
src/World/VirtualChunk.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/VirtualChunk.cpp.i
.PHONY : src/World/VirtualChunk.cpp.i

src/World/VirtualChunk.s: src/World/VirtualChunk.cpp.s
.PHONY : src/World/VirtualChunk.s

# target to generate assembly for a file
src/World/VirtualChunk.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/VirtualChunk.cpp.s
.PHONY : src/World/VirtualChunk.cpp.s

src/World/World.o: src/World/World.cpp.o
.PHONY : src/World/World.o

# target to build an object file
src/World/World.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/World.cpp.o
.PHONY : src/World/World.cpp.o

src/World/World.i: src/World/World.cpp.i
.PHONY : src/World/World.i

# target to preprocess a source file
src/World/World.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/World.cpp.i
.PHONY : src/World/World.cpp.i

src/World/World.s: src/World/World.cpp.s
.PHONY : src/World/World.s

# target to generate assembly for a file
src/World/World.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/World.cpp.s
.PHONY : src/World/World.cpp.s

src/World/WorldManager.o: src/World/WorldManager.cpp.o
.PHONY : src/World/WorldManager.o

# target to build an object file
src/World/WorldManager.cpp.o:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/WorldManager.cpp.o
.PHONY : src/World/WorldManager.cpp.o

src/World/WorldManager.i: src/World/WorldManager.cpp.i
.PHONY : src/World/WorldManager.i

# target to preprocess a source file
src/World/WorldManager.cpp.i:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/WorldManager.cpp.i
.PHONY : src/World/WorldManager.cpp.i

src/World/WorldManager.s: src/World/WorldManager.cpp.s
.PHONY : src/World/WorldManager.s

# target to generate assembly for a file
src/World/WorldManager.cpp.s:
	$(MAKE) -f CMakeFiles/Server.dir/build.make CMakeFiles/Server.dir/src/World/WorldManager.cpp.s
.PHONY : src/World/WorldManager.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Server"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Block/Block.o"
	@echo "... src/Block/Block.i"
	@echo "... src/Block/Block.s"
	@echo "... src/Block/BlockList.o"
	@echo "... src/Block/BlockList.i"
	@echo "... src/Block/BlockList.s"
	@echo "... src/Block/BlockMaterial.o"
	@echo "... src/Block/BlockMaterial.i"
	@echo "... src/Block/BlockMaterial.s"
	@echo "... src/Block/Scripts/Basics/StairScript.o"
	@echo "... src/Block/Scripts/Basics/StairScript.i"
	@echo "... src/Block/Scripts/Basics/StairScript.s"
	@echo "... src/Block/Scripts/BlockScript.o"
	@echo "... src/Block/Scripts/BlockScript.i"
	@echo "... src/Block/Scripts/BlockScript.s"
	@echo "... src/Block/Scripts/RegisterBlockScripts.o"
	@echo "... src/Block/Scripts/RegisterBlockScripts.i"
	@echo "... src/Block/Scripts/RegisterBlockScripts.s"
	@echo "... src/Block/SoundBlock.o"
	@echo "... src/Block/SoundBlock.i"
	@echo "... src/Block/SoundBlock.s"
	@echo "... src/Chat/ChatManager.o"
	@echo "... src/Chat/ChatManager.i"
	@echo "... src/Chat/ChatManager.s"
	@echo "... src/Config/Config.o"
	@echo "... src/Config/Config.i"
	@echo "... src/Config/Config.s"
	@echo "... src/Database/DatabaseManager.o"
	@echo "... src/Database/DatabaseManager.i"
	@echo "... src/Database/DatabaseManager.s"
	@echo "... src/Entity/Entity.o"
	@echo "... src/Entity/Entity.i"
	@echo "... src/Entity/Entity.s"
	@echo "... src/Entity/EntityPlayer.o"
	@echo "... src/Entity/EntityPlayer.i"
	@echo "... src/Entity/EntityPlayer.s"
	@echo "... src/Entity/LivingEntity.o"
	@echo "... src/Entity/LivingEntity.i"
	@echo "... src/Entity/LivingEntity.s"
	@echo "... src/Entity/Position.o"
	@echo "... src/Entity/Position.i"
	@echo "... src/Entity/Position.s"
	@echo "... src/Inventory/Inventory.o"
	@echo "... src/Inventory/Inventory.i"
	@echo "... src/Inventory/Inventory.s"
	@echo "... src/Inventory/InventoryPlayer.o"
	@echo "... src/Inventory/InventoryPlayer.i"
	@echo "... src/Inventory/InventoryPlayer.s"
	@echo "... src/Inventory/Item.o"
	@echo "... src/Inventory/Item.i"
	@echo "... src/Inventory/Item.s"
	@echo "... src/Inventory/ItemStack.o"
	@echo "... src/Inventory/ItemStack.i"
	@echo "... src/Inventory/ItemStack.s"
	@echo "... src/Inventory/Scripts/Basics/ItemBlockScript.o"
	@echo "... src/Inventory/Scripts/Basics/ItemBlockScript.i"
	@echo "... src/Inventory/Scripts/Basics/ItemBlockScript.s"
	@echo "... src/Inventory/Scripts/ItemScript.o"
	@echo "... src/Inventory/Scripts/ItemScript.i"
	@echo "... src/Inventory/Scripts/ItemScript.s"
	@echo "... src/Inventory/Scripts/RegisterItemScripts.o"
	@echo "... src/Inventory/Scripts/RegisterItemScripts.i"
	@echo "... src/Inventory/Scripts/RegisterItemScripts.s"
	@echo "... src/Main/Server.o"
	@echo "... src/Main/Server.i"
	@echo "... src/Main/Server.s"
	@echo "... src/Network/NetworkEncryption.o"
	@echo "... src/Network/NetworkEncryption.i"
	@echo "... src/Network/NetworkEncryption.s"
	@echo "... src/Network/NetworkException.o"
	@echo "... src/Network/NetworkException.i"
	@echo "... src/Network/NetworkException.s"
	@echo "... src/Network/NetworkExceptionData.o"
	@echo "... src/Network/NetworkExceptionData.i"
	@echo "... src/Network/NetworkExceptionData.s"
	@echo "... src/Network/NetworkManager.o"
	@echo "... src/Network/NetworkManager.i"
	@echo "... src/Network/NetworkManager.s"
	@echo "... src/Network/NetworkPacket.o"
	@echo "... src/Network/NetworkPacket.i"
	@echo "... src/Network/NetworkPacket.s"
	@echo "... src/Network/NetworkSession.o"
	@echo "... src/Network/NetworkSession.i"
	@echo "... src/Network/NetworkSession.s"
	@echo "... src/Network/Opcode.o"
	@echo "... src/Network/Opcode.i"
	@echo "... src/Network/Opcode.s"
	@echo "... src/Network/PacketHandler.o"
	@echo "... src/Network/PacketHandler.i"
	@echo "... src/Network/PacketHandler.s"
	@echo "... src/Scripting/ScriptManager.o"
	@echo "... src/Scripting/ScriptManager.i"
	@echo "... src/Scripting/ScriptManager.s"
	@echo "... src/Util/AABB.o"
	@echo "... src/Util/AABB.i"
	@echo "... src/Util/AABB.s"
	@echo "... src/World/Chunk.o"
	@echo "... src/World/Chunk.i"
	@echo "... src/World/Chunk.s"
	@echo "... src/World/VirtualChunk.o"
	@echo "... src/World/VirtualChunk.i"
	@echo "... src/World/VirtualChunk.s"
	@echo "... src/World/World.o"
	@echo "... src/World/World.i"
	@echo "... src/World/World.s"
	@echo "... src/World/WorldManager.o"
	@echo "... src/World/WorldManager.i"
	@echo "... src/World/WorldManager.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

